##This is a pair of functions that can be used to solve for the 
##inverse of a matrix.  The inverse of the matrix is cached so that
##it does not need to be solved again as long as the matrix is unchanged.
##The matrix must first be passed to makeCacheMatrix.
##The list returned by makeCacheMatrix can then be passed to cacheSolve.

##The makeCacheMatrix function creates a special "matrix",
##which is really a list containing functions to
##1. set the value of the matrix
##2. get the value of the matrix
##3. set the value of the inverse of the matrix in cache
##4. get the value of the inverse of the matrix from cache

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        ##define function to set the value of the matrix
        set <- function(y) {
                x <<- y
                m <<- NULL ##clear previously cached inverse of matrix
        }
        ##define function to get the value of the matrix
        get <- function() x
        ##define function to cache the value of the inverse of the matrix
        setsolve <- function(solve) m <<- solve 
        ##define function to get the cached value of the inverse of the matrix
        getsolve <- function() m
        ##construct list containing the functions above
        list(set = set, get = get,
             setsolve = setsolve,
             getsolve = getsolve)
}

##This function solves for the inverse of the special "matrix" 
##returned by makeCacheMatrix above. If the inverse has already 
##been solved (and the matrix has not changed), then cacheSolve
##retrieves the inverse from the cache.
##This function should only be passed the makeCacheMatrix list as
##an argument and not the original matrix

cacheSolve <- function(x, ...) {
        ##set m to the cached value of the inverse of the matrix
        ##in the list generated by function makeCacheMatrix
        m <- x$getsolve()
        ##check if cached inverse of the matrix exists in m
        ##if so, print status message and return cached inverse of matrix
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        ##get the value of the matrix from the list
        data <- x$get()
        ##solve for the inverse of the matrix
        m <- solve(data, ...)
        ##cache the inverse of the matrix
        x$setsolve(m)
        ##return inverse of the matrix
        m
}

##Test Script
##x <- matrix(1:4,2,2) ##create test matrix
##y <- makeCacheMatrix(x) ##create list of functions using matrix data
##z <- cacheSolve(y) ##return inverse of matrix using cache if available
##x ##return original matrix
##z ##return inverse of matrix
##x %*% z ##multiply matrix by inverse to get identity matrix
##identity matrix should be square, have 1's on diaganol and 0's elsewehere

